### ISSUE TITLE
Script is reading from OK

### ISSUE THREAD

**Issue by Seba0** [Ma7moud3ly/micro-repl#17]
Place two big letters OK in script, script will be read begining from OK

**Comment by Ma7moud3ly** [comment]
Yeah it's a good catch..  Actually I use OK to detect the end of script execution when I turn from silent execution mode CTRL + A -> Exit CTRL + D -> REPL mode CTRL + B
I will work to fix it.
Thanks..


![image](https://github.com/Ma7moud3ly/micro-repl/assets/16342931/b0cc22fc-5ae9-4278-a816-03e9562807fd)

**Comment by Ma7moud3ly** [comment]
fixed
