### ISSUE TITLE
This device is not supported!  Right now we support only Micro...

### ISSUE THREAD

**Issue by davefes** [Ma7moud3ly/micro-repl#2]
I believe I am using an OTG adapter as a mouse works on my Samsung Galaxy A03s.

I am supplying an external 5V to my ESP32 DevkitC.

Do I need another adapter?

Thanks.

**Comment by Wind-stormger** [comment]
Same issue.

SONY XQ-AT72, Android 12

ESP32S3 micropython 1.19.1, REPL output from USB , ❌

ESP32S2 micropython 1.19.1, REPL output from USB , ❌

ESP32S2 micropython 1.19.1, REPL output from UART , ❌

**Comment by Ma7moud3ly** [comment]
Hello @davefes @Wind-stormger 
Thank you for testing the app.
Actually this issue happens because I made an incorrect filter for devices by vendor Id.. 
```
    private val supportedVendors = listOf(
        11914 //Raspberry Pi (Trading) Limited
    )
```
I thought 11914 related to MicroPython itself not Raspberry Pi Pico 😅

So I will find another filtering method other than the vendor id. 
Thanks

**Comment by Wind-stormger** [comment]
@Ma7moud3ly Is it ready for esp32？

**Comment by Ma7moud3ly** [comment]
@Wind-stormger It should be ready.
Please test the new release and let me know.

**Comment by Ma7moud3ly** [comment]
@FakeChimera01 Have you tried V1.1 ?

**Comment by Ma7moud3ly** [comment]
@FakeChimera01 
For filtering MicroPython boards I need some help from those who have different boards.
I asked here for help but didn't get any response.
https://github.com/orgs/micropython/discussions/11272

**Comment by Wind-stormger** [comment]
Me too, V1.1 not work on ESP32S2 or ESP32S3.

**Comment by Ma7moud3ly** [comment]
Hello guys,
In the new version, I have added an option to approve any port manually and add it to the white list.
All your boards are expected to be working now..
Thanks for your help.
<img width="300" src='https://user-images.githubusercontent.com/16342931/233200143-a805cb6a-0579-4bce-bd05-a3f4e9682664.jpg'/>

for update -> https://play.google.com/store/apps/details?id=micro.repl.ma7moud3ly

**Comment by davefes** [comment]
Working for me on ESP32.  Very nice job.  The ESP32 dev board is even powered from my phone so can program on the go!

Syntax highlighting is probably a big ask.

Something odd happens when you rotate the phone, you lose the connection ... I am confident that it is not my data cable connections.
