### ISSUE TITLE
add option to select usb device

### ISSUE THREAD

**Issue by iamrouf** [Ma7moud3ly/micro-repl#21]
I use a usb hub with my phone with a wireless mouse and keyboard ,,from the app there is no way to select diffrent usb device .
why this is a problem because the app keeps selecting the wireless reciver of my wireless mouse and keyboard .. hopefully it will be fixed 
![Screenshot_20240427-113259_Micro REPL](https://github.com/Ma7moud3ly/micro-repl/assets/168258073/1f5f1c90-934d-463a-b718-f20e1ba7fb76)

**Comment by Ma7moud3ly** [comment]
Thank you for suggesting this feature.
I have made some changes to allow the user to connect to one of multiple devices or change the connected device.
This gonna be released soon 
![image](https://github.com/Ma7moud3ly/micro-repl/assets/16342931/4030c849-623d-4b47-8ae6-7a7a4a90b408)
