### ISSUE TITLE
Regular crashing

### ISSUE THREAD

**Issue by fons0** [Ma7moud3ly/micro-repl#22]
In version 1.4 I had regular crashing when connected to any micropython device but with no pattern I could figure out. I just installed 1.5 and it consistently happening when I try to edit code stored on the device, had to reinstall 1.4.

Aside from this issue I love the app, keep up the great work.

Currently using Pi pico and Samsung Galaxy s22 Android 14

**Comment by CGsama** [comment]
I think it is the code editor crashing. I do a work around that change the file extension to .txt, edit it, then change extension back.

**Comment by Ma7moud3ly** [comment]
Thank you @fons0 @CGsama.
I found the problem that makes the code editor crashes. 1.6 will be released very soon.
