### ISSUE TITLE
I cant open the pico w files in the file maneger can someone please help me


### ISSUE THREAD

**Issue by TinkererLabs** [Ma7moud3ly/micro-repl#24]

**Comment by Ma7moud3ly** [comment]
Hello @TinkererLabs 
Please can you provide more info about MicroPython version you are using with Pico W.
Because the files manager is tested with **RPI_PICO_W-20240222-v1.22.2.uf2**  and works fine.

**Comment by TinkererLabs** [comment]
Like the newest version doesnt work but the one before it does like it just crashes

**Comment by Ma7moud3ly** [comment]
@TinkererLabs The new update v1.6 is available on google play, please test it and let me know about any issues.
Thanks
