### ISSUE TITLE
Issue pasting code in terminal (indentation)

### ISSUE THREAD

**Issue by Afnankabiro** [Ma7moud3ly/micro-repl#26]
There are some issues with indentation while pasting code in the terminal

Device: Realme 7 Pro 
OS: Android 11
Board: ESP32
Recording below-

https://github.com/Ma7moud3ly/micro-repl/assets/102663023/a21aea6e-c5b6-40ff-8285-fc87469d0267

**Comment by Ma7moud3ly** [comment]
Hello @Afnankabiro 
While your script has some issues, but a multiline code will have a better behavior in 1.6.
Thanks

**Comment by Alex777ddd** [comment]
Fails Every time, version 1.6 1.5. phone redmi 9a(two of them)

**Comment by Alex777ddd** [comment]
> Fails Every time, when press open in editor, on chosen file. version 1.6 1.5. phone redmi 9a(two of them)

Fails when open.py files, when open other files, .txt for example, it's opening for editing
