### ISSUE TITLE
App still crashes in editor v1.6

### ISSUE THREAD

**Issue by kamper-core** [Ma7moud3ly/micro-repl#31]
For the first time app works fine an i can write something but syntax don't highlight, after save if I trying open this file or open editor app crashed. And interaction with board fs haven't effect. (arduino nano rp2040 connect, micropython v1.23

**Comment by kamper-core** [comment]
FS interact resolved by installing micropython 1.19. But app still crashes.

**Comment by Sam2much96** [comment]
I have this same issue also. 

Device: Samsung AO2

**Comment by Seba0** [comment]
I have this same issue. When i try to edit file with **.py** extension then it crash.
When i compile app with sora-editor in version 0.22.2 then it don't crashes. 

Device: Galaxy A50.

**Comment by Ma7moud3ly** [comment]
This crash should have been fixed in V1.7 
https://github.com/Ma7moud3ly/micro-repl/issues/33
