### ISSUE TITLE
FilesManager.decodeFiles doesn't support tuples without size

### ISSUE THREAD

**Issue by antweb** [Ma7moud3ly/micro-repl#5]
Hi!

I'm trying to get the file explorer feature to work on the flow3r badge ([ESP32-S3 / MicroPython](https://docs.flow3r.garden/badge/hardware_specs.html) with a bunch of customizations) and ran into the following issue:

`FilesManager.decodeFiles()` is assuming that all elements returned by `os.ilistdir()` have four tuple members. But according to the [MicroPython docs](https://docs.micropython.org/en/latest/library/os.html#os.ilistdir), the last element (size) is optional.

From what I can see, the `size` value in `MicroFile` is not used anyway, so it should be safe to fall back to `0`/`-1`.
I've created a [a potential fix](https://github.com/antweb/micro-repl/tree/support-ilistdir-without-size). Let me know what you think about the approach.

**Comment by Ma7moud3ly** [comment]
Hello @antweb
I'm sorry, I'm too late to see that issue. But thanks to your suggestion it should be fixed now ✅
I hope you made a pull request since then it would have helped a lot.
Thanks
